export const MAIN_ROUTE = "/"
export const ADD_POSTS_ROUTE = "/add-posts"
export const ADD_TOOLS_ROUTE = "/add-tools"
export const ADD_BOOKS_ROUTE = "/add-books"
export const ADD_NEWS_ROUTE = "/add-news"